"""Constants for Growatt Export Controller."""

DOMAIN = "growatt_export_controller"

CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_INVERTER_SERIAL = "inverter_serial"
CONF_DEVICE_PASSWORD_PREFIX = "device_password_prefix"
CONF_COMMAND_SERVER_URL = "command_server_url"
CONF_DEFAULT_EXPORT_PERCENTAGE = "default_export_percentage"
CONF_DEFAULT_METER_ENABLED = "default_meter_enabled"

CONF_PRICE_SENSOR = "price_sensor"
CONF_PRICE_THRESHOLD = "price_threshold"
CONF_PRICE_RECOVERY_THRESHOLD = "price_recovery_threshold"
CONF_PRICE_INCLUDE_TAX = "price_include_tax"
CONF_PRICE_TRIGGER_METER_ENABLED = "price_trigger_meter_enabled"
CONF_PRICE_TRIGGER_EXPORT_PERCENTAGE = "price_trigger_export_percentage"
CONF_PRICE_NORMAL_METER_ENABLED = "price_normal_meter_enabled"
CONF_PRICE_NORMAL_EXPORT_PERCENTAGE = "price_normal_export_percentage"
CONF_PRICE_AUTOMATION_ENABLED = "price_automation_enabled"

DEFAULT_COMMAND_SERVER_URL = "https://server.growatt.com"
DEFAULT_DEVICE_PASSWORD_PREFIX = "growatt"
DEFAULT_EXPORT_PERCENTAGE = 100
DEFAULT_METER_ENABLED = False

DEFAULT_PRICE_AUTOMATION_ENABLED = False
DEFAULT_PRICE_THRESHOLD = 0.05
DEFAULT_PRICE_RECOVERY_THRESHOLD = 0.06
DEFAULT_PRICE_INCLUDE_TAX = True
DEFAULT_PRICE_TRIGGER_METER_ENABLED = True
DEFAULT_PRICE_TRIGGER_EXPORT_PERCENTAGE = 100
DEFAULT_PRICE_NORMAL_METER_ENABLED = False
DEFAULT_PRICE_NORMAL_EXPORT_PERCENTAGE = 100
